require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - 'gemfiles/*'

Metrics:
  Enabled: false
Bundler/DuplicatedGem:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/SpecFilePathFormat:
  Exclude:
    - 'spec/outrigger/cops/**/*.rb'
Style/Documentation:
  Enabled: false
Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec